name: Govulncheck

on:
  schedule:
    - cron: '00 15 * * MON'
  workflow_dispatch: {}

permissions:
  issues: write

jobs:
  call-govulncheck:
    uses: yottta/github-workflows/.github/workflows/govulncheck.yaml@add-govulncheck
    with:
      enabled: true
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
