name: Govulncheck

on:
  schedule:
    - cron: '00 00 * * SUN'
  workflow_dispatch: {}

permissions:
  issues: write
  contents: read

jobs:
  run-govulncheck:
    if: github.ref == 'refs/heads/main'
    uses: yottta/github-workflows/.github/workflows/govulncheck.yaml@main
    with:
      enabled: true
      branch-to-scan: 'main'
    secrets:
      issues_gh_token: ${{ secrets.GITHUB_TOKEN }}
